document.addEventListener("DOMContentLoaded", () => {
  const questions = [
[
    "Jak se jmenuješ?",
    "Odkud jsi?",
    "Kolik je ti let?",
    "Máš sourozence?",
    "Kde bydlíš?",
    "Co děláš ve volném čase?",
    "Jaké máš oblíbené jídlo?",
    "Kdy máš narozeniny?",
    "Kdo je tvůj nejlepší přítel?",
    "Kde jsi se narodil?",
    "Proč se učíš česky?",
    "V kolik hodin vstáváš?",
    "Kolik knih máš doma?",
    "Který film se ti líbí nejvíce?",
    "Jaký sport tě baví?",
    "Co chceš dělat zítra?",
    "Odkud pochází tvoje rodina?",
    "Čím cestuješ do školy?",
    "Odkdy studuješ češtinu?",
    "Dokdy plánuješ zůstat doma?",
    "Jak často chodíš do kina?",
    "Bez koho bys nebyl šťastný?",
    "Ke komu chodíš na návštěvu?",
    "O kom často mluvíš?",
    "S kým trávíš volný čas?",
    "Bez čeho nemůžeš žít?",
    "K čemu potřebuješ tu knihu?",
    "O čem si dnes povídal?",
    "S čím se učíš nejraději?",
    "Pro co jsi vděčný?",
    "Čí je to batoh?",
    "Jak se cítíš dnes?",
    "Kam půjdeš odpoledne?",
    "Máš rád hudbu?",
    "Jak se máš?",
    "Mluvíš česky?",
    "Kdy jsi naposledy byl na výletě?",
    "Kdo ti pomáhá s úkoly?",
    "Kde se potkáme zítra?",
    "Proč tě baví čtení?",
    "V kolik hodin končí škola?",
    "Kolik peněz máš u sebe?",
    "Který den v týdnu je tvůj oblíbený?",
    "Jaký je tvůj oblíbený film?",
    "Co budeš dělat o víkendu?",
    "Odkud máš tuhle informaci?",
    "Čím se chceš živit v budoucnu?",
    "Odkdy znáš svého kamaráda?",
    "Dokdy budeš pracovat na projektu?",
    "Jak často sportuješ?",
    "Bez koho se cítíš osaměle?",
    "Ke komu se obracíš pro radu?",
    "O kom jsi se učil dnes?",
    "S kým chodíš na procházky?",
    "Bez čeho se neobejdeš při cestování?",
    "K čemu slouží tato aplikace?",
    "O čem sníš?",
    "S čím máš problém?",
    "Pro co bys utratil výhru?",
    "Čí je to dům?",
    "Jak jsi spokojený se školou?",
    "Kam se chystáš v létě?",
    "Máš rád sport?",
    "Jak se cítíš po ránu?",
    "Mluvíš anglicky?",
    "Kdy odjíždíš na dovolenou?",
    "Kdo tě inspiruje?",
    "Kde pracuje tvoje maminka?",
    "Proč chodíš do školy?",
    "V kolik hodin jíš oběd?",
    "Kolik hodin denně spíš?",
    "Který jazyk se učíš?",
    "Jaký je tvůj oblíbený předmět?",
    "Co tě baví nejvíce?",
    "Odkud pochází tvůj pes?",
    "Čím jezdíš do práce?",
    "Odkdy se zajímáš o hudbu?",
    "Dokdy bude trvat prázdniny?",
    "Jak často chodíš na výlety?",
    "Bez koho bys nemohl žít?",
    "Ke komu chodíš na kroužky?",
    "O kom jsi slyšel dnes?",
    "S kým se učíš doma?",
    "Bez čeho se nedá vařit?",
    "K čemu používáš mobil?",
    "O čem je ten film?",
    "S čím ti mohu pomoci?",
    "Pro co se zajímáš?",
    "Čí je to kolo?",
    "Jak se učíš nové věci?",
    "Kam jdeš po škole?",
    "Máš rád zvířata?",
    "Jak se připravuješ na test?",
    "Mluvíš německy?",
    "Kdy přijedeš domů?",
    "Kdo je tvůj učitel?",
    "Kde nakupuješ oblečení?",
    "Proč se směješ?",
    "V kolik hodin začíná film?",
    "Kolik hodin jsi dnes spal?",
    "Který sport tě baví nejvíce?",
    "Jaký je tvůj oblíbený recept?",
    "Co si dáš k večeři?",
    "Odkud jsi získal tuto informaci?",
    "Čím se bavíš ve volném čase?",
    "Odkdy chodíš do školy?",
    "Dokdy zůstaneš vzhůru?",
    "Jak často telefonuješ s kamarády?",
    "Bez koho bys nešel na oslavu?",
    "Ke komu se chystáš zítra?",
    "O kom sníš?",
    "S kým hraješ fotbal?",
    "Bez čeho nejde udělat domácí úkol?",
    "K čemu ti slouží počítač?",
    "O čem přemýšlíš?",
    "S čím si nejlépe rozumíš?",
    "Pro co jsi ochotný pracovat?",
    "Čí je to auto?"
]

  ];

  const button = document.getElementById("generateBtn");
  const box = document.getElementById("questionBox");

  button.addEventListener("click", () => {
    const randomIndex = Math.floor(Math.random() * questions.length);
    box.textContent = questions[randomIndex];
  });
});
